[package]
name = "banker-algorithm"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "symbols"
opt-level = 3
overflow-checks = true
lto = true
codegen-units = 1
panic = "abort"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
rand = "0.8.5"
